# @format

version: "3.8"
services:
    app:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        container_name: skill-nest-server
        ports:
            - "8001:8001"
        environment:
            NODE_ENV: "development"

        depends_on:
            - dynamodb-local

        volumes:
            - ./app:/app
        command: npm run dev

    dynamodb-local:
        command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
        image: "amazon/dynamodb-local:latest"
        container_name: dynamodb-local
        ports:
            - "8000:8000"
        volumes:
            - "./docker/dynamodb:/home/dynamodblocal/data"
        working_dir: /home/dynamodblocal
        environment:
            REGION: "ap-south-1"
